Adjusted the installation of GKE and also commented out build + test for faster verification of deploy

diff --git a/.github/workflows/build-services.yaml b/.github/workflows/build-services.yaml
--- a/.github/workflows/build-services.yaml
+++ b/.github/workflows/build-services.yaml
@@ -9,138 +9,138 @@ permissions:
   contents: read
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up JDK 23
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: '23'
-
-      - name: Filter changed paths
-        id: filter
-        uses: dorny/paths-filter@v2
-        with:
-          filters: |
-            appointment-service:
-              - 'appointment-service/**'
-            clinic-service:
-              - 'clinic-service/**'
-            user-service:
-              - 'user-service/**'
-            API-gateway:
-              - 'API-gateway/**'
-            common-dto:
-              - 'common-dto/**'
-
-      # Build common-dto always (shared dependency)
-      - name: Build common-dto
-        working-directory: common-dto
-        run: mvn clean install
-
-      - name: Build appointment service
-        if: steps.filter.outputs.appointment-service == 'true'
-        working-directory: appointment-service
-        run: mvn clean install
-
-      - name: Build clinic service
-        if: steps.filter.outputs.clinic-service == 'true'
-        working-directory: clinic-service
-        run: mvn clean install
-
-      - name: Build user service
-        if: steps.filter.outputs.user-service == 'true'
-        working-directory: user-service
-        run: mvn clean install
-
-      - name: Build API Gateway
-        if: steps.filter.outputs.API-gateway == 'true'
-        working-directory: API-gateway
-#        env:
-#          spring.security.oauth2.resourceserver.jwt.issuer-uri: ${{secrets.SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.ISSUER-URI}}
-        run: mvn clean install
-
-      - name: Docker compose build
-        run: |
-          docker compose build
-          mkdir dockerimages
-          docker save baconagent/appointment-service -o ./dockerimages/appointment-service.tar
-          docker save baconagent/clinic-service -o ./dockerimages/clinic-service.tar
-          docker save baconagent/api-gateway -o ./dockerimages/api-gateway.tar
-          docker save baconagent/user-service -o ./dockerimages/user-service.tar
-
-      - name: Upload Docker images as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: docker-images
-          path: ./dockerimages/
-
-  test:
-    runs-on: ubuntu-latest
-    needs: build
-
-    steps:
-      - uses: actions/checkout@v4
-        name: Checkout docker compose file
-        with:
-          sparse-checkout: |
-            docker-compose.yml
-          sparse-checkout-cone-mode: false
-
-      - name: Create docker images folder
-        run: |
-          docker images
-          mkdir dockerimages
-
-      - name: Download Docker images artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: docker-images
-          path: ./dockerimages/
-
-      - name: Load Docker Images
-        run: |
-          docker load -i ./dockerimages/appointment-service.tar
-          docker load -i ./dockerimages/clinic-service.tar
-          docker load -i ./dockerimages/api-gateway.tar
-          docker load -i ./dockerimages/user-service.tar
-          docker images
-
-      # Bring up the stack, including observability (assumes these services are in docker-compose.yml)
-      - name: Run Docker Containers (incl. Grafana, Loki, Prometheus, Tempo)
-        run: |
-          docker compose up -d
-          docker ps
-
-      - name : Test RabbitMQ request
-        run: |
-          sleep 10s
-          curl -u guest:guest \
-             -H "Content-Type: application/json" \
-             -X PUT \
-             -d '{"auto_delete": false, "durable": true, "arguments": {}}' \
-             http://localhost:15672/api/queues/%2f/delete_clinic_queue
-          sleep 10s
-          curl 'http://localhost:8080/api/clinic/publish?message=test'
-      - name: Validate Docker logs
-        run: |
-          docker compose --profile all logs appointment-service > appointment-service.txt
-          if grep -q "test" appointment-service.txt; then
-            echo "Log entry containing test message found!"
-          else
-            echo "Log entry containing test message not found!"
-            docker compose logs
-            exit 1
-          fi
+#  build:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v4
+#
+#      - name: Set up JDK 23
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin'
+#          java-version: '23'
+#
+#      - name: Filter changed paths
+#        id: filter
+#        uses: dorny/paths-filter@v2
+#        with:
+#          filters: |
+#            appointment-service:
+#              - 'appointment-service/**'
+#            clinic-service:
+#              - 'clinic-service/**'
+#            user-service:
+#              - 'user-service/**'
+#            API-gateway:
+#              - 'API-gateway/**'
+#            common-dto:
+#              - 'common-dto/**'
+#
+#      # Build common-dto always (shared dependency)
+#      - name: Build common-dto
+#        working-directory: common-dto
+#        run: mvn clean install
+#
+#      - name: Build appointment service
+#        if: steps.filter.outputs.appointment-service == 'true'
+#        working-directory: appointment-service
+#        run: mvn clean install
+#
+#      - name: Build clinic service
+#        if: steps.filter.outputs.clinic-service == 'true'
+#        working-directory: clinic-service
+#        run: mvn clean install
+#
+#      - name: Build user service
+#        if: steps.filter.outputs.user-service == 'true'
+#        working-directory: user-service
+#        run: mvn clean install
+#
+#      - name: Build API Gateway
+#        if: steps.filter.outputs.API-gateway == 'true'
+#        working-directory: API-gateway
+##        env:
+##          spring.security.oauth2.resourceserver.jwt.issuer-uri: ${{secrets.SPRING.SECURITY.OAUTH2.RESOURCESERVER.JWT.ISSUER-URI}}
+#        run: mvn clean install
+#
+#      - name: Docker compose build
+#        run: |
+#          docker compose build
+#          mkdir dockerimages
+#          docker save baconagent/appointment-service -o ./dockerimages/appointment-service.tar
+#          docker save baconagent/clinic-service -o ./dockerimages/clinic-service.tar
+#          docker save baconagent/api-gateway -o ./dockerimages/api-gateway.tar
+#          docker save baconagent/user-service -o ./dockerimages/user-service.tar
+#
+#      - name: Upload Docker images as artifact
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: docker-images
+#          path: ./dockerimages/
+#
+#  test:
+#    runs-on: ubuntu-latest
+#    needs: build
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#        name: Checkout docker compose file
+#        with:
+#          sparse-checkout: |
+#            docker-compose.yml
+#          sparse-checkout-cone-mode: false
+#
+#      - name: Create docker images folder
+#        run: |
+#          docker images
+#          mkdir dockerimages
+#
+#      - name: Download Docker images artifact
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: docker-images
+#          path: ./dockerimages/
+#
+#      - name: Load Docker Images
+#        run: |
+#          docker load -i ./dockerimages/appointment-service.tar
+#          docker load -i ./dockerimages/clinic-service.tar
+#          docker load -i ./dockerimages/api-gateway.tar
+#          docker load -i ./dockerimages/user-service.tar
+#          docker images
+#
+#      # Bring up the stack, including observability (assumes these services are in docker-compose.yml)
+#      - name: Run Docker Containers (incl. Grafana, Loki, Prometheus, Tempo)
+#        run: |
+#          docker compose up -d
+#          docker ps
+#
+#      - name : Test RabbitMQ request
+#        run: |
+#          sleep 10s
+#          curl -u guest:guest \
+#             -H "Content-Type: application/json" \
+#             -X PUT \
+#             -d '{"auto_delete": false, "durable": true, "arguments": {}}' \
+#             http://localhost:15672/api/queues/%2f/delete_clinic_queue
+#          sleep 10s
+#          curl 'http://localhost:8080/api/clinic/publish?message=test'
+#      - name: Validate Docker logs
+#        run: |
+#          docker compose --profile all logs appointment-service > appointment-service.txt
+#          if grep -q "test" appointment-service.txt; then
+#            echo "Log entry containing test message found!"
+#          else
+#            echo "Log entry containing test message not found!"
+#            docker compose logs
+#            exit 1
+#          fi
 
   deploy:
     runs-on: ubuntu-latest
-    needs:
-      - build
+#    needs:
+#      - build
 #      - test commenting out test due to time pressure. Testing itself is done wrong and will need to be redone anyways.
 
     steps:
@@ -214,17 +214,14 @@ jobs:
 
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
+        with:
+          install_components: gke-gcloud-auth-plugin
 
       - name: Authenticate kubectl with GKE
         run: |
           gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
             --region ${{ secrets.GCP_REGION }} \
             --project ${{ secrets.GCP_PROJECT_ID }}
-
-      - name: Install gke-gcloud-auth-plugin
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
 
       - name: Rollout restart changed deployments
         run: |
@@ -245,8 +242,8 @@ jobs:
   cleanup:
     runs-on: ubuntu-latest
     needs:
-      - build
-      - test
+#      - build
+#      - test
       - deploy
     if: ${{ always() }}
 
