Testing updated yaml file with docker integration

diff --git a/.github/workflows/build-services.yaml b/.github/workflows/build-services.yaml
--- a/.github/workflows/build-services.yaml
+++ b/.github/workflows/build-services.yaml
@@ -10,7 +10,7 @@ jobs:
     steps:
       # Checkout the repository so we can inspect the changes
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
       # Set up JDK 23
       - name: Set up JDK 23
         uses: actions/setup-java@v3
@@ -56,3 +56,79 @@ jobs:
         if: steps.filter.outputs.API-gateway == 'true'
         working-directory: API-gateway
         run: mvn clean install
+
+      - name: Docker compose build
+        run: |
+            docker compose --profile all build
+            mkdir dockerimages
+            docker save baconagent/appointmentservice -o ./dockerimages/appointmentservice.tar
+            docker save baconagent/clinicservice -o ./dockerimages/clinicservice.tar
+            docker save baconagent/api-gateway -o ./dockerimages/api-gateway.tar
+            docker save baconagent/postgres_appointmentsdb -o ./dockerimages/postgres_appointmentsdb.tar
+            docker save baconagent/rabbitmq -o ./dockerimages/rabbitmq.tar
+
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+
+    steps:
+      - uses: actions/checkout@v4
+        name: Checkout docker compose file
+        with:
+          sparse-checkout: |
+            docker-compose.yml
+          sparse-checkout-cone-mode: false
+
+      - name: Create docker images folder
+        run: |
+          docker images
+          mkdir dockerimages
+
+      - name: Download Docker images artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: docker-images
+          path: ./dockerimages/
+
+      - name: Load Docker Images
+        run: |
+          docker load -i ./dockerimages/postgres_appointmentsdb
+          docker load -i ./dockerimages/rabbitmq
+          docker load -i ./dockerimages/appointmentservice
+          docker load -i ./dockerimages/clinicservice
+          docker load -i ./dockerimages/api-gateway
+          docker images
+
+      - name: Run Docker Containers
+        run: |
+          docker compose --profile all up -d
+          docker ps
+      - name : Test RabbitMQ request
+        run: |
+          sleep 10s
+          curl 'http://localhost:8080/api/clinic/publish?message=test'
+      - name: Validate Docker logs
+        run: |
+          docker compose --profile all logs appointmentservice > appointmentservice.txt
+          if grep -q "test" appointmentservice.txt; then
+            echo "Log entry containing test message found!"
+          else
+            echo "Log entry containing test message not found!"
+            docker compose logs
+            exit 1
+          fi
+
+
+  cleanup:
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - test
+    if: ${{ always() }}
+
+    steps:
+      - uses: geekyeggo/delete-artifact@v5
+        name: Cleanup artifacts
+        with:
+          name: |
+            docker-images
